name: Go

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # No Windows this time. Some tests expect Unix-style paths.
        os: [ ubuntu-latest, macos-latest ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        # Due to https://github.com/go-openapi/swag/issues/59
        go-version: 1.16

    - name: Setup gotestsum
      uses: autero1/action-gotestsum@v1.0.0
      with:
        gotestsum_version: 1.7.0

    - name: Test
      run: gotestsum --format short-verbose -- -race -timeout=20m -coverprofile=coverage_txt -covermode=atomic ./...

    - uses: codecov/codecov-action@v2
      with:
        files: coverage_txt

  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
      with:
        args: --timeout=5m